
<div class="jumbotron">
    Roll'n API is a 30 minute talk by <a href="https://about.me/tom_h_anderson">Tom Anderson</a> in which an API is created from the design tool ORM Designer
    to a fully functional API serving data in 10 minutes.  Examples are then shown for connecting to ODM resources
    and existing relational databases and questions tend take 5 to 10 minutes.
</div>


<h1>2014-02-10 PHP Meetup in San Francisco</h1>
<iframe width="560" height="315" src="//www.youtube.com/embed/5apFQF3VE3M" frameborder="0" allowfullscreen></iframe>

