
<div class="jumbotron">
    Roll'n API is a 30 minute talk by <a href="https://about.me/tom_h_anderson">Tom Anderson</a> 
    in which an API is created from the design tool ORM Designer
    to a fully functional API serving data in 10 minutes.  Coding is executed live and there are no slides.
    Examples are then shown for connecting to ODM resources
    and existing relational databases.  Other topics which may be covered are API security and API documentation.
</div>

<h1>Presentations</h1>

<h2>2014-02-10 PHP Meetup in San Francisco</h2>

Given to an audience of about 30, the entire talk is recorded here:<br>
<iframe width="560" height="315" src="//www.youtube.com/embed/5apFQF3VE3M" frameborder="0" allowfullscreen></iframe>

