
<div class="jumbotron">
    <img src="/images/rollnapi.png" align="left" style="margin: 5px;">
    <h1><?php echo sprintf($this->translate('Welcome to %sRoll\'n API%s'), '<span class="color-orange">', '</span>') ?></h1>
    <p>This website will guide you to build a Hypertext Application Language (HAL) Application Programming Interface (API) from database design to final relase using the very latest in PHP technology.</p>

    </p>
        This application uses a sqlite database which may be changed in the local.php configuration.
    </p>
</div>


<div class="row">
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('1. Clone the project') ?></h3>
            </div>
            <div class="panel-body">
                <p>Using <a href="http://git-scm.com/">git</a>, fork <a href="https://github.com/StukiOrg/RollNApi">the RollNApi project</a>
                and clone the repository locally.  The root directory of your cloned copy will hereafter be referred to as ~</p>

                <p>
                    Run <b>~/bin/install</b>
                </p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('2. Configure the project') ?></h3>
            </div>
            <div class="panel-body">
                <p>
                    Copy <b>~/config/autoload/local.php.dist</b> to <b>~/config/autoload/local.php</b> and edit for your database.
                </p>
            </div>
        </div>
    </div>


    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('3. Design your ERD') ?></h3>
            </div>
            <div class="panel-body">
                <p>Use <a href="http://www.orm-designer.com">ORM Designer</a> to open <b>~/documentation/RollNApi.ormdesigner2</b></p>

                <p>Create your Entity Relationship Diagram using any method you'd like except many-to-many relationships.  For these releations use table between the two
                relations with a relation to each and and id.</p>

                <p>For guidance you can reference <a href="https://github.com/etreedb/etreedb-db/raw/master/documentation/orm_designer/db.ormdesigner">
                a complete entity relationship diagram</a> and the documentation on the <a href="http://www.orm-designer.com">ORM Designer</a> web site.
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('4. Export your diagram and install it') ?></h3>
            </div>
            <div class="panel-body">
                <p>When your ERD is complete click "Export to ORM".  This will create files in <b>~/module/Db/config/xml</b>  If you need to re-export
                your diagram be sure to delete all the files in the <b>~/module/Db/config/xml</b> directory first.
                </p>

                <p>
                    Run <b>~/bin/rebuild</b>
                </p>

                <p>
                    Your database schema and HAL API will be created.
                </p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('5. Optional:  Add Faker data') ?></h3>
            </div>
            <div class="panel-body">
                <p>
                    You may add dummy data to your database.  Edit <b>~/module/Db/src/Db/Fixture/Faker.php</b> and copy the
                    <code>
                        $populator->addEntity('Db\Entity\Name', 10);
                    </code>
                    line and add a line for for each entity.
                </p>

                <p>
                    Run <b>~/bin/fixtures</b>
                </p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('6. Build your API') ?></h3>
            </div>
            <div class="panel-body">
                <p>
                    Run <b>bin/apirebuild</b> to create the API.  This will output your api endpoints.
                <p>
                    Run the application ~: <b>php -S localhost:8080 -t public/ public/index.php</b>
                </p>
                <p>
                    Browse to <a href="http://localhost:8080/admin">http://localhost:8080/admin</a> to see the Apigility console.  Use an HTTP client to query your API endpoints.
                </p>
            </div>
        </div>
    </div>

</div>

<center>
    <img src="/images/cake.jpg">
</center>
