<div class="jumbotron">
    <img src="/images/rollnapi.png" align="left" style="margin: 5px;">
    <h1><?php echo sprintf($this->translate('Welcome to %sRoll\'n API%s'), '<span class="color-orange">', '</span>') ?></h1>
    <p>This website will walk you through building an API from database design to final relase using the very latest in PHP technology.</p>
    <p style="clear: both">You will be using
        <ul>
            <li><a href="http://www.orm-designer.com">ORM Designer</a></li>
            <li><a href="http://framework.zend.com">Zend Framework</a></li>
            <li><a href="http://www.doctrine-project.org">Doctrine Project</a></li>
            <li><a href="http://www.apigility.com">Apigility</a></li>
        </ul>

        These technologies support <a href="http://www.doctrine-project.org/blog/database-support-doctrine2.html">many databases</a>.
    </p>
    <p class="alert alert-success"><b>
        If you need any help please <a href="mailto:support@rollnapi.com">contact us</a>.
    </b></p>
</div>

<div class="row">
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('1. Clone the project') ?></h3>
            </div>
            <div class="panel-body">
                <p>Using <a href="http://git-scm.com/">git</a>, fork <a href="https://github.com/StukiOrg/RollNApi">the RollNApi project</a>
                and clone a copy to work on locally.  The root directory of your cloned copy will hereafter be referred to as ~</p>

                <p>
                    Once you have cloned the project run <a href="http://www.getcomposer.org">Composer</a>.  This will install all the
                    supporting libraries for your API.  The command, once you download Composer, is <i>php composer.phar install --dev</i>
                </p>

                <p>
                    Copy ~/config/autoload/local.php.dist to ~/config/autoload/local.php and edit for your database.
                </p>
                <p>
                    From ~ run <i>php public/index.php development enable</i>
                </p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('2. Design your database') ?></h3>
            </div>
            <div class="panel-body">
                <p>Download and install <a href="http://www.orm-designer.com">ORM Designer</a> then open ~/documentation/RollNApi.ormdesigner2</p>

                <p>Create your database using any method you'd like except many-to-many relationships.  For these releations use table between the two
                relations with a relation to each and and id.</p>

                <p>The RollNApi project only supports one module out of the box so if you get fancy and create more you've been warned.</p>

                <p>For guidance you can reference <a href="https://github.com/etreedb/etreedb-db/raw/master/documentation/orm_designer/db.ormdesigner">
                a complete entity relationship diagram, or ERD</a>, and the documentation on the <a href="http://www.orm-designer.com">ORM Designer</a> web site.
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('3. Export you diagram') ?></h3>
            </div>
            <div class="panel-body">
                <p>When your ERD is complete click "Export to ORM".  This will create files in ~/module/Db/config/xml  If you need to re-export
                your diagram be sure to delete all the files in the ~/module/Db/config/xml directory first.
                </p>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('4. Create your database') ?></h3>
            </div>
            <div class="panel-body">
                <p>Manually create your database using the tool of your choice.

                <p>Using <a href="http://git-scm.com/">git</a>, fork <a href="https://github.com/StukiOrg/RollNApi">the RollNApi project</a>
                and clone a copy to work on locally.  The root directory of your cloned copy will hereafter be referred to as ~</p>
            </div>
        </div>
    </div>
</div>